<?php
if (!defined('ABSPATH')) die('-1');

add_action( 'vc_load_default_templates_action','seo_home_template' ); // Hook in
 
function seo_home_template() {
    $data               = array(); // Create new array
    $data['name']       = __( 'SEO Home', 'my-text-domain' ); // Assign name for your custom template
    $data['weight']     = 0; // Weight of your template in the template list
    
    $data['custom_class'] = 'custom_template_for_vc_custom_template'; // CSS class name
    $data['content']    = <<<CONTENT
        
        [vc_row full_width="stretch_row_content_no_spaces"][vc_column][seo_slide][/vc_column][/vc_row][vc_row css=".vc_custom_1499793885818{padding-top: 70px !important;padding-bottom: 90px !important;}"][vc_column][vc_column_text el_class="seo-header"]
<h2 style="text-align: center;">our service</h2>
<p style="text-align: center;">lorem ipsum dolor sit amet, consectetuer
adipiscing elit, sed diam.</p>
[/vc_column_text][vc_row_inner css=".vc_custom_1499793837705{margin-top: 30px !important;}"][vc_column_inner width="1/3"][seo_service_two title="SEO Optimization" desc="Lorem ipsum dolor sit aet constetuer adipiscing elit sednonummy" type="2" external_link="#" icon="1" upload_icon="1776"][/vc_column_inner][vc_column_inner width="1/3"][seo_service_two title="Web Analysis" desc="Lorem ipsum dolor sit aet constetuer adipiscing elit sednonummy" type="2" external_link="#" icon="1" upload_icon="1775"][/vc_column_inner][vc_column_inner width="1/3"][seo_service_two title="Email Marketing" desc="Lorem ipsum dolor sit aet constetuer adipiscing elit sednonummy" type="2" external_link="#" choose_icon="fa fa-envelope-o"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row full_width="stretch_row_content_no_spaces" equal_height="yes" css=".vc_custom_1499797448778{padding-right: 90px !important;}"][vc_column width="1/2"][vc_row_inner css=".vc_custom_1499968109236{background-image: url(http://crazyupload.online/wp-content/uploads/2017/06/nature-sky-sunset-man.jpeg?id=310) !important;}" el_class="bg-arrow"][vc_column_inner offset="vc_hidden-sm vc_hidden-xs"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column width="1/2"][vc_row_inner css=".vc_custom_1499968143808{padding-left: 60px !important;}"][vc_column_inner][vc_custom_heading text="reputation management" font_container="tag:h2|text_align:left|color:%23020202" google_fonts="font_family:Nova%20Script%3Aregular|font_style:400%20regular%3A400%3Anormal" el_class="seo-header"][vc_column_text]Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam. nibh euismo
tincidunt ut laoreet dolore magna aliquam erat volutpat.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_tta_accordion active_section="1" css=".vc_custom_1499968184689{padding-left: 60px !important;}"][vc_tta_section title="Identifying Problem Source" tab_id="1499795835171-650ba514-7006"][vc_column_text]Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam. nibh
euismo tincidunt ut laoreet dolore magna aliquam erat volutpat.[/vc_column_text][/vc_tta_section][vc_tta_section title="Reducing the visiblity of the negative information" tab_id="1499795913373-b69a0b14-1d01"][vc_column_text]I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.[/vc_column_text][/vc_tta_section][vc_tta_section title="Protecting brand integrity" tab_id="1499795918667-219c8400-f33b"][vc_column_text]I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.[/vc_column_text][/vc_tta_section][/vc_tta_accordion][/vc_column][/vc_row][vc_row full_width="stretch_row_content_no_spaces" css=".vc_custom_1499797749814{padding-top: 10px !important;padding-bottom: 40px !important;background-color: #19b5fe !important;}"][vc_column][seo_cta_two title="Grow your Business!" desc="Place your Business at the top of search Engines and Expand." link_text="Get Started" type="2" external_link="#"][/vc_column][/vc_row][vc_row css=".vc_custom_1499879118383{padding-top: 70px !important;padding-bottom: 90px !important;}"][vc_column][vc_custom_heading text="awesome team" font_container="tag:h2|text_align:center" google_fonts="font_family:Nova%20Script%3Aregular|font_style:400%20regular%3A400%3Anormal" el_class="seo-header"][vc_column_text]
<p style="text-align: center;">lorem ipsum dolor sit amet, consectetuer
adipiscing elit, sed diam.</p>
[/vc_column_text][vc_row_inner css=".vc_custom_1499879296386{margin-top: 30px !important;}"][vc_column_inner width="1/4"][seo_team title="Jonathon Doe" desc="Design Expert" facebook="#" twitter="#" youtube="#" google="#" skype="#" instagram="#" upload_team="187"][/vc_column_inner][vc_column_inner width="1/4"][seo_team title="Jonathon Doe" desc="Design Expert" facebook="#" twitter="#" youtube="#" google="#" skype="#" instagram="#" upload_team="187"][/vc_column_inner][vc_column_inner width="1/4"][seo_team title="Jonathon Doe" desc="Design Expert" facebook="#" twitter="#" youtube="#" google="#" skype="#" instagram="#" upload_team="187"][/vc_column_inner][vc_column_inner width="1/4"][seo_team title="Jonathon Doe" desc="Design Expert" facebook="#" twitter="#" youtube="#" google="#" skype="#" instagram="#" upload_team="187"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row full_width="stretch_row" css=".vc_custom_1499883486772{padding-top: 60px !important;padding-bottom: 100px !important;background-image: url(http://crazyupload.online/wp-content/uploads/2017/07/01_SEO_Home-page_01.jpg?id=1797) !important;}" el_class="bg-computer"][vc_column width="1/2" offset="vc_col-lg-offset-0 vc_col-lg-6"][vc_row_inner][vc_column_inner][vc_custom_heading text="Best Solutions For Your Business" google_fonts="font_family:Nova%20Script%3Aregular|font_style:400%20regular%3A400%3Anormal" el_class="seo-header" css=".vc_custom_1500799404190{margin-bottom: 20px !important;}"][/vc_column_inner][/vc_row_inner][vc_column_text]Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip. sed diam noummy nibh eui smod tincidunt ut laoreet dolore magna aliquam erat volutpat.[/vc_column_text][vc_btn title="Contact Now" shape="square"][/vc_column][/vc_row][vc_row css=".vc_custom_1499793885818{padding-top: 70px !important;padding-bottom: 90px !important;}"][vc_column][vc_column_text el_class="seo-header"]
<h2 style="text-align: center;"><strong>LATEST NEWS</strong></h2>
<p style="text-align: center;">lorem ipsum dolor sit amet, consectetuer
adipiscing elit, sed diam.</p>
[/vc_column_text][vc_row_inner equal_height="yes" el_class="home-post"][vc_column_inner][vc_basic_grid post_type="post" max_items="3" grid_id="vc_gid:1501354130125-ab2ff002-a6c5-9"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row full_width="stretch_row" css=".vc_custom_1499884981575{padding-top: 70px !important;padding-bottom: 90px !important;background-color: #23b5fa !important;}"][vc_column][vc_column_text el_class="seo-header"]
<h2 style="text-align: center;"><strong>cLIENTS SAY</strong></h2>
<p style="text-align: center;">lorem ipsum dolor sit amet, consectetuer
adipiscing elit, sed diam.</p>
[/vc_column_text][vc_row_inner][vc_column_inner width="1/3"][seo_testimonial clint_name="jHON dOE" title="Graphic Designer" desc="Lorem ipsum dolor sit amet, consectetuer adiping elit, sed diam nonummy nibh euismod tinunt ut laoreet dolore magna aliquam." clint_image="187"][/vc_column_inner][vc_column_inner width="1/3"][seo_testimonial clint_name="jHON dOE" title="Graphic Designer" desc="Lorem ipsum dolor sit amet, consectetuer adiping elit, sed diam nonummy nibh euismod tinunt ut laoreet dolore magna aliquam." clint_image="187"][/vc_column_inner][vc_column_inner width="1/3"][seo_testimonial clint_name="jHON dOE" title="Graphic Designer" desc="Lorem ipsum dolor sit amet, consectetuer adiping elit, sed diam nonummy nibh euismod tinunt ut laoreet dolore magna aliquam." clint_image="187"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row full_width="stretch_row_content_no_spaces"][vc_column][seo_map water="#eeedef"]36/A | lan 5[/seo_map][/vc_column][/vc_row]
CONTENT;
  
    vc_add_default_templates( $data );
}

//
//add_action( 'vc_load_default_templates_action','seo_bout_template' ); // Hook in
// 
//function seo_about_template() {
//    $data               = array(); // Create new array
//    $data['name']       = __( 'SEO About', 'my-text-domain' ); // Assign name for your custom template
//    $data['weight']     = 0; // Weight of your template in the template list
//    
//    $data['custom_class'] = 'custom_template_for_vc_custom_template'; // CSS class name
//    $data['content']    = <<<CONTENT
//    [vc_row full_width="stretch_row_content" css=".vc_custom_1501268222232{background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner css=".vc_custom_1501268209753{background-image: url(http://crazyupload.online/wp-content/uploads/2017/03/nature-sky-sunset-man.jpeg?id=1708) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column_inner width="1/2" css=".vc_custom_1501271659030{background-color: #ffffff !important;}" offset="vc_col-lg-offset-6 vc_col-lg-6 vc_col-md-offset-6 vc_col-md-6 vc_col-sm-offset-6"][vc_column_text el_class="seo-header" css=".vc_custom_1499929699018{padding-top: 50px !important;padding-right: 100px !important;padding-bottom: 50px !important;padding-left: 40px !important;}"]
//<h2>our vission</h2>
//Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diamnon ummy nibh euismod tincidunt ut laoreet dolore magna alquamerat volutpat. Ut wisi enim ad minim veniam, quis nostrud ipsum dolor sit amet consectetuer adipiscing elit, sed diamnon ummy nibh euismod tincidunt ut laoreet dolore magna aliquamerat volutpat. Ut wisi enim ad minm aliquip ex ea commodo consquat. Duisr autem vel eum iriure dolor in.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner css=".vc_custom_1501268209753{background-image: url(http://crazyupload.online/wp-content/uploads/2017/03/nature-sky-sunset-man.jpeg?id=1708) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column_inner width="1/2" css=".vc_custom_1501271675450{background-color: #ffffff !important;}" offset="vc_col-lg-offset-0 vc_col-lg-6 vc_col-md-offset-0 vc_col-md-6 vc_col-sm-offset-0"][vc_column_text el_class="seo-header" css=".vc_custom_1499929699018{padding-top: 50px !important;padding-right: 100px !important;padding-bottom: 50px !important;padding-left: 40px !important;}"]
//<h2>our vission</h2>
//Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diamnon ummy nibh euismod tincidunt ut laoreet dolore magna alquamerat volutpat. Ut wisi enim ad minim veniam, quis nostrud ipsum dolor sit amet consectetuer adipiscing elit, sed diamnon ummy nibh euismod tincidunt ut laoreet dolore magna aliquamerat volutpat. Ut wisi enim ad minm aliquip ex ea commodo consquat. Duisr autem vel eum iriure dolor in.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner css=".vc_custom_1501268209753{background-image: url(http://crazyupload.online/wp-content/uploads/2017/03/nature-sky-sunset-man.jpeg?id=1708) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column_inner css=".vc_custom_1501271691660{background-color: #ffffff !important;}" offset="vc_col-lg-offset-6 vc_col-lg-6 vc_col-md-offset-6 vc_col-md-6 vc_col-sm-offset-6"][vc_column_text el_class="seo-header" css=".vc_custom_1499929699018{padding-top: 50px !important;padding-right: 100px !important;padding-bottom: 50px !important;padding-left: 40px !important;}"]
//<h2>our vission</h2>
//Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diamnon ummy nibh euismod tincidunt ut laoreet dolore magna alquamerat volutpat. Ut wisi enim ad minim veniam, quis nostrud ipsum dolor sit amet consectetuer adipiscing elit, sed diamnon ummy nibh euismod tincidunt ut laoreet dolore magna aliquamerat volutpat. Ut wisi enim ad minm aliquip ex ea commodo consquat. Duisr autem vel eum iriure dolor in.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner css=".vc_custom_1501268209753{background-image: url(http://crazyupload.online/wp-content/uploads/2017/03/nature-sky-sunset-man.jpeg?id=1708) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column_inner width="1/2" css=".vc_custom_1501271700829{background-color: #ffffff !important;}" offset="vc_col-lg-offset-0 vc_col-lg-6 vc_col-md-offset-0 vc_col-md-6 vc_col-sm-offset-0"][vc_column_text el_class="seo-header" css=".vc_custom_1499929699018{padding-top: 50px !important;padding-right: 100px !important;padding-bottom: 50px !important;padding-left: 40px !important;}"]
//<h2>our vission</h2>
//Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diamnon ummy nibh euismod tincidunt ut laoreet dolore magna alquamerat volutpat. Ut wisi enim ad minim veniam, quis nostrud ipsum dolor sit amet consectetuer adipiscing elit, sed diamnon ummy nibh euismod tincidunt ut laoreet dolore magna aliquamerat volutpat. Ut wisi enim ad minm aliquip ex ea commodo consquat. Duisr autem vel eum iriure dolor in.[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1499930015979{margin-top: 70px !important;padding-bottom: 90px !important;}"][vc_column][vc_column_text el_class="seo-header"]
//<h2 style="text-align: center;">awesome team member</h2>
//<p style="text-align: center;">lorem ipsum dolor sit amet, consectetuer
//adipiscing elit, sed diam.</p>
//[/vc_column_text][vc_row_inner][vc_column_inner width="1/4"][seo_team title="Jonathon Doe" desc="Design Expert" facebook="#" twitter="#" youtube="#" google="#" skype="#" instagram="#" upload_team="187"][/vc_column_inner][vc_column_inner width="1/4"][seo_team title="Jonathon Doe" desc="Design Expert" facebook="#" twitter="#" youtube="#" google="#" skype="#" instagram="#" upload_team="187"][/vc_column_inner][vc_column_inner width="1/4"][seo_team title="Jonathon Doe" desc="Design Expert" facebook="#" twitter="#" youtube="#" google="#" skype="#" instagram="#" upload_team="187"][/vc_column_inner][vc_column_inner width="1/4"][seo_team title="Jonathon Doe" desc="Design Expert" facebook="#" twitter="#" youtube="#" google="#" skype="#" instagram="#" upload_team="187"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/4"][seo_team title="Jonathon Doe" desc="Design Expert" facebook="#" twitter="#" youtube="#" google="#" skype="#" instagram="#" upload_team="187"][/vc_column_inner][vc_column_inner width="1/4"][seo_team title="Jonathon Doe" desc="Design Expert" facebook="#" twitter="#" youtube="#" google="#" skype="#" instagram="#" upload_team="187"][/vc_column_inner][vc_column_inner width="1/4"][seo_team title="Jonathon Doe" desc="Design Expert" facebook="#" twitter="#" youtube="#" google="#" skype="#" instagram="#" upload_team="187"][/vc_column_inner][vc_column_inner width="1/4"][seo_team title="Jonathon Doe" desc="Design Expert" facebook="#" twitter="#" youtube="#" google="#" skype="#" instagram="#" upload_team="187"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row full_width="stretch_row" css=".vc_custom_1499930203605{padding-top: 10px !important;padding-bottom: 40px !important;background-color: #19b5fe !important;}"][vc_column][seo_cta_two title="Grow your Business!" desc="Place your Business at the top of search Engines and Expand." link_text="Get Started" type="2" external_link="#"][/vc_column][/vc_row]
//    CONTENT;
//  
//    vc_add_default_templates( $data );
//}
